# Generated by Django 4.0.6 on 2022-07-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='desc',
            field=models.TextField(default='Description'),
        ),
    ]
