# Generated by Django 4.0.6 on 2022-07-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_thing_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thing',
            options={'verbose_name': 'Our Thing', 'verbose_name_plural': 'Our Things'},
        ),
        migrations.AlterField(
            model_name='thing',
            name='desc',
            field=models.TextField(blank=True, default='Description'),
        ),
    ]
